version: 0.2

env:
  variables:
    BUILD_ENV: "production"
    CLOUDFRONT_DIST_ID: ""

phases:
  install:
    runtime-versions:
      nodejs: 12.x

    commands:
      # temporary fix of YARN cert issue
      # TODO: clean it up...
      - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
      -
      # Update packages.
      - apt-get update -y -q

      # Install @angular/cli and app dependencies.
      - echo Installing source NPM dependencies...
      - npm install -g @angular/cli
      - npm install

  build:
    commands:
      # Build Angular application.
      - echo Build started on `date`
      - npm run build -- --configuration=${BUILD_ENV}

      - docker build -t $DOCKER_REPOSITORY_URI:latest
      - docker tag $DOCKER_REPOSITORY_URI:latest $DOCKER_REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo Build has been completed.
      - echo Pushing Docker images.
      - docker push $DOCKER_REPOSITORY_URI:latest
      - docker push $DOCKER_REPOSITORY_URI:$IMAGE_TAG

      - echo Writing an image definition file.
      - printf '{"Image":"%s"}' $DOCKER_REPOSITORY_URI:$IMAGE_TAG > image-def.json

artifacts:
  files:
    - image-def.json

  secondary-artifacts:
    artifact1:
      base-directory: $CODEBUILD_SRC_DIR
      discard-paths: no
      files:
        - '**/*'
