version: 0.2

env:
  variables:
    CODE_CLIMATE_REPORTER_ID: ""
    GIT_BRANCH: master
    CI_NAME: CodeBuild

phases:

  install:
    runtime-versions:
      docker: 18

  build:
    commands:
      - echo Runninging code quality tools.
      - docker build --build-arg ENV_CONFIGURATION=production --build-arg CODE_CLIMATE_REPORTER_ID=$CODE_CLIMATE_REPORTER_ID --build-arg CI_NAME=$CI_NAME --build-arg GIT_COMMIT_SHA=$CODEBUILD_RESOLVED_SOURCE_VERSION --build-arg GIT_BRANCH=$GIT_BRANCH -f Dockerfile_quality .
      - echo Code Quality check is passed
