version: 0.2

env:
  variables:
    DOCKER_REPOSITORY_URI: ""

phases:

  install:
    runtime-versions:
      docker: 18

  pre_build:
    commands:
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}

      - echo Logging in to Amazon ECR.
      - aws --version
      - $(aws ecr get-login --no-include-email --region us-east-1)

  build:
    commands:
      - echo Build has been started.
      - echo Building a Docker image.
      - docker build -t $DOCKER_REPOSITORY_URI:latest .
      - docker tag $DOCKER_REPOSITORY_URI:latest $DOCKER_REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo Build has been completed.
      - echo Pushing Docker images.
      - docker push $DOCKER_REPOSITORY_URI:latest
      - docker push $DOCKER_REPOSITORY_URI:$IMAGE_TAG

      - echo Writing an image definition file.
      - printf '{"Image":"%s"}' $DOCKER_REPOSITORY_URI:$IMAGE_TAG > image-def.json
      - cat image-def.json

artifacts:
  files:
    - image-def.json

  secondary-artifacts:
    artifact1:
      base-directory: $CODEBUILD_SRC_DIR
      discard-paths: no
      files:
        - "**/*"
